name: Keep Streamlit App Alive
on:
  schedule:
    - cron: '0 */6 * * *'   # Runs every 6 hours
  workflow_dispatch:        # Allows manual triggers

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -s -o /dev/null -w "HTTP status: %{http_code}\n" https://recepty.streamlit.app/
